- name: Deploy repo to boxes
  hosts: targets
  become: true
  tasks:
    - name: Ensure /opt/database exists
      file:
        path: /opt/database
        state: directory
        mode: '0755'
    
    - name: Copy contents of database to /opt/test2
      copy:
        src: ./database/
        dest: /opt/database/
        owner: root
        group: root
        mode: preserve
    
    - name: 